# Generated by Django 5.1.13 on 2026-09-24 21:06

from django.db import migrations


def crear_grupo_usuario(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    grupo, creado = Group.objects.get_or_create(name='Usuario')

    permisos = [
        'add_categoria',
        'change_categoria',
        'delete_categoria',
        'view_categoria',

        'add_proyecto',
        'change_proyecto',
        'delete_proyecto',
        'view_proyecto',

        'add_subtarea',
        'change_subtarea',
        'delete_subtarea',
        'view_subtarea',

        'add_tarea',
        'change_tarea',
        'delete_tarea',
        'view_tarea',
    ]

    for permiso in permisos:
        permiso_obj = Permission.objects.get(
            codename=permiso,
            content_type__app_label='app'
        )
        grupo.permissions.add(permiso_obj)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(crear_grupo_usuario),
    ]